language: node_js
node_js:
  # LTS version
  - "9.3.0"
cache:
  directories:
    - node_modules
install:
  - npm install
# command to run tests
script:
    - npm test 
    - npm test -- --coverage
    - npm install coveralls --save

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
